
from sqlalchemy.dialects import sqlite
from sqlalchemy.sql.elements import ClauseElement, ColumnElement
from sqlalchemy import or_
from sqlalchemy.orm import Query
from .filter_part import FilterPart
from ..wrappers.wrapper_comparison import ComparisonWrapper
from ..wrappers.wrapper_logical import LogicalWrapper


class FilterGenerator:
    def __init__(self, commands: list[FilterPart], ):
        self.filters: None | ClauseElement = None
        self.columns: list[ColumnElement] = []
        self._parse_init(commands)


    @staticmethod
    def clause_element_to_string(command: ClauseElement) -> str:
        """Compile a ClauseElement to a string."""
        return str(command.compile(dialect=sqlite.dialect(), compile_kwargs={"literal_binds": True}))

    @staticmethod
    def query_to_string(query: Query) -> str:
        """Transform a query to a string"""
        return str(query.statement.compile(dialect=sqlite.dialect(), compile_kwargs={"literal_binds": True}))

    def _parse_init(
            self,
            commands: list['FilterPart'],
    ) -> None:
        if self.filters:
            raise ValueError(f"Can not call <_make_command> more than one time. ({self})")
        result, _ = self._make_command(commands)
        self.filters = result

    def _make_command(
            self,
            commands: list['FilterPart'],
            i: int = 0,
            consume_parenthesis: bool = False
    ) -> tuple[ClauseElement, int]:
        prev_command = None
        first_command = True
        close_parenthesis = False

        while i < len(commands) and not close_parenthesis:
            cf: FilterPart = commands[i]
            if not cf:
                if cf.logger: cf.logger.error(
                    "Unknown colum : '%s' from '%s'. %s",
                    cf.str_column, cf.unformatted_string, cf.string_to_columns.keys(),
                )
                i += 1
                continue
            elif not isinstance(cf.logic_operator, LogicalWrapper):
                # This should not happen since FilterPart's logic_operator returns a LogicalWrapper
                if cf.logger: cf.logger.critical(
                    "Can not use '%s' as '%s'. Problem generated by '%s' (%s)",
                    cf.logic_operator, LogicalWrapper, id(cf), cf.str_column
                )
                i += 1
                continue
            elif not isinstance(cf.comp_operator, ComparisonWrapper):
                # If there is no comparison to do, there is no
                # filter to add.
                i += 1
                continue

            col = cf.column
            self.columns.append(col)

            # if col is None:
            #    if cf.logger: cf.logger.error(
            #        "Unknown colum : '%s' from '%s'. %s",
            #        cf.str_column, cf.unformatted_string, cf.string_to_columns.keys(),
            #    )

            if not first_command and cf.start_parenthesis:
                # We have a prev_command and a start_parenthesis should be opened
                # --> Lets works on the parenthesis inside a new _make_command
                new_element, new_i = self._make_command(
                    commands,
                    i,
                    consume_parenthesis=False
                )
                cf.logger.info("YO")
                prev_command = cf.logic_operator(prev_command, new_element)
                i = new_i
                continue

            elif first_command and cf.start_parenthesis and not consume_parenthesis:
                # We should define a prev_command and
                # consume this parenthesis
                cf.logger.warning(f"1, {cf.start_parenthesis}, {first_command}, {cf} {i}")
                new_element, new_i = self._make_command(
                    commands,
                    i,
                    consume_parenthesis=True
                )
                prev_command = new_element
                i = new_i
                first_command = False
                cf.logger.warning(f"2', {cf.start_parenthesis}, {first_command}, {cf} {new_i}")
                continue

            elif not first_command:
                # We have a prev_command and a start_parenthesis should be opened
                # --> Lets works on the parenthesis inside a new _make_command
                cf.logger.info(f"2, {cf.start_parenthesis}, {first_command}, {cf} {i}")
                prev_command = cf.logic_operator(
                    prev_command,
                    cf.comp_operator(
                        col,
                        cf.comp_value
                    )
                )

            elif first_command and cf.start_parenthesis and consume_parenthesis:
                # We can pass this parenthesis without using _make_command
                cf.logger.info(f"1', {cf.start_parenthesis}, {first_command}, {cf} {i}")
                prev_command = cf.comp_operator(col, cf.comp_value)
                first_command = False

            elif first_command:
                # We should define a prev_command
                prev_command = cf.comp_operator(col, cf.comp_value)
                first_command = False

            else:
                raise NotImplementedError(
                    f"Missing condition in {type(self)}._make_command. To handle '{cf}' with "
                    f"locals={locals()}")


            i += 1
            close_parenthesis = cf.close_parenthesis

        return prev_command, i

    @property
    def safe_filters(self) -> ClauseElement:
        """Return the filter build inside this FilterGenerator. If no filter has been
        built, a filter always True is returned."""
        if self.filters is None:
            return or_(True, True)
        return  self.filters


    def __str__(self):
        """When a filter is built, returns this filter transformed in string."""
        if self.filters is not None:
            return self.clause_element_to_string(self.filters)
        return super().__str__()
