from typing import Union

from sqlalchemy import true
from sqlalchemy.dialects import sqlite
from sqlalchemy.orm import Query
from sqlalchemy.sql.elements import ClauseElement, ColumnElement

from ..wrappers.wrapper_comparison import ComparisonWrapper
from ..wrappers.wrapper_logical import LogicalWrapper
from .filter_part import FilterPart


class FilterGenerator:
    """Generate a self.filters that can be used inside a query objet using
    a list of FilterPart."""
    FilterPart = FilterPart

    def __init__(
        self,
        commands: list[FilterPart],
    ):
        self.filters: None | ColumnElement = None
        self.filter_parts: list[FilterPart] = commands
        self.columns: list[ColumnElement] = []
        self._parse_init(commands)

    @staticmethod
    def clause_element_to_string(command: ClauseElement) -> str:
        """Compile a ClauseElement to a string."""
        return str(
            command.compile(
                dialect=sqlite.dialect(), compile_kwargs={"literal_binds": True}
            )
        )

    @staticmethod
    def query_to_string(query: Query) -> str:
        """Transform a query to a string"""
        return str(
            query.statement.compile(
                dialect=sqlite.dialect(), compile_kwargs={"literal_binds": True}
            )
        )

    def _parse_init(
        self,
        commands: list["FilterPart"],
    ) -> None:
        if self.filters:
            raise ValueError(
                f"Can not call <_make_command> more than one time. ({self})"
            )
        result, _ = self._make_command(commands)
        self.filters = result

    def _make_command(
        self,
        commands: list["FilterPart"],
        i: int = 0,
        consume_parenthesis: bool = False,
    ) -> tuple[Union[ColumnElement, None], int]:
        prev_command: None | ColumnElement = None
        first_command: bool = True
        close_parenthesis: bool = False

        while i < len(commands) and not close_parenthesis:
            cf: FilterPart = commands[i]
            if not cf or cf.column is None:
                if cf.logger:
                    cf.logger.error(
                        "Unknown colum : '%s' from '%s'. %s",
                        cf.str_column,
                        cf.unformatted_string,
                        cf.string_to_columns.keys(),
                    )
                i += 1
                continue

            col = cf.column
            self.columns.append(col)

            if not isinstance(cf.logic_operator, LogicalWrapper):
                # This should not happen since FilterPart's logic_operator returns a LogicalWrapper
                if cf.logger:
                    cf.logger.critical(
                        "Can not use '%s' as '%s'. Problem generated by '%s' (%s)",
                        cf.logic_operator,
                        LogicalWrapper,
                        id(cf),
                        cf.str_column,
                    )
                i += 1
                continue
            if not isinstance(cf.comp_operator, ComparisonWrapper):
                # If there is no comparison to do, there is no
                # filter to add.
                i += 1
                continue

            # if col is None:
            #    if cf.logger: cf.logger.error(
            #        "Unknown colum : '%s' from '%s'. %s",
            #        cf.str_column, cf.unformatted_string, cf.string_to_columns.keys(),
            #    )

            if not first_command and cf.start_parenthesis:
                # We have a prev_command and a start_parenthesis should be opened
                # --> Lets works on the parenthesis inside a new _make_command
                new_element, new_i = self._make_command(
                    commands, i, consume_parenthesis=False
                )

                prev_command = cf.logic_operator(prev_command, new_element)
                i = new_i
                continue

            if (
                first_command
                and cf.start_parenthesis
                and not consume_parenthesis
            ):
                # We should define a prev_command and
                # consume this parenthesis
                new_element, new_i = self._make_command(
                    commands, i, consume_parenthesis=True
                )
                prev_command = new_element
                i = new_i
                first_command = False
                continue

            if not first_command:
                # We have a prev_command and a start_parenthesis should be opened
                # --> Lets works on the parenthesis inside a new _make_command
                prev_command = cf.logic_operator(
                    prev_command, cf.comp_operator(col, cf.comp_value)
                )

            elif first_command and cf.start_parenthesis and consume_parenthesis:
                # We can pass this parenthesis without using _make_command
                prev_command = cf.comp_operator(col, cf.comp_value)
                first_command = False

            elif first_command:
                # We should define a prev_command
                prev_command = cf.comp_operator(col, cf.comp_value)
                first_command = False

            else:
                raise NotImplementedError(
                    f"Missing condition in {type(self)}._make_command. To handle '{cf}' with "
                    f"locals={locals()}"
                )

            i += 1
            close_parenthesis = cf.close_parenthesis

        return prev_command, i

    @property
    def safe_filters(self) -> ColumnElement:
        """Return the filter build inside this FilterGenerator. If no filter has been
        built, a filter always True is returned."""
        if self.filters is None:
            return true()
        return self.filters

    def __str__(self):
        """When a filter is built, returns this filter transformed in string."""
        if self.filters is not None:
            return self.clause_element_to_string(self.filters)
        return super().__str__()
