import pdfplumber
import unicodedata
import os
from typing import Iterator, Callable, Any
import bs4


class FileToText:
    @staticmethod
    def combine_accents(text: str) -> str:
        """Combines only accent with there partener.
        Sometime when i parsed pdf i have ^a instead of â
        `e instead of è ...
        This function fix this issue.
    
        GENERATED BY ChatGPT
        """
        accent_unicode_map = {
            '´': '\u0301',  # acute
            '`': '\u0300',  # grave
            'ˆ': '\u0302',  # circumflex
            '¨': '\u0308',  # diaeresis
            '¸': '\u0327',  # cedilla
        }
    
        result = []
        i = 0
        while i < len(text):
            char = text[i]
            if char in accent_unicode_map and i+1 < len(text):
                # Accent before letter → combine
                combined = text[i+1] + accent_unicode_map[char]
                result.append(unicodedata.normalize('NFC', combined))
                i += 2  # Skip next letter
            else:
                result.append(char)
                i += 1
        return ''.join(result)
    
    @classmethod
    def pdf_to_text(cls, pdf_path: str) -> Iterator[str]:
        """Yield each page of a pdf as a string."""
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                text = page.extract_text()
    
                yield cls.combine_accents(text)

    @classmethod
    def html_to_text(cls, path: str) -> Iterator[str]:
        """Transform a  bs4.BeautifulSoup to a string"""
        # Load your HTML file
        with open(path, "r", encoding="utf-8") as f:
            html_content = f.read()

        # Parse the HTML
        soup = bs4.BeautifulSoup(html_content, "html.parser")

        yield soup.get_text(strip=True)

    conversion_map: dict[str, Callable[..., Iterator[str]]] = {
        "pdf": pdf_to_text,
        "html": html_to_text,
    }

    @classmethod
    def convert_to_text_file(cls, path: str, txt_path: str, var_type: str | None = None, **kwargs):
        """Convert a file into a .txt"""

        for pages in cls.convert_to_string(path, var_type, **kwargs):
            with open(txt_path, "w", encoding="utf8") as flux:
                flux.write(pages)

    @classmethod
    def convert_to_string(cls, path: str, var_type: str | None = None, **kwargs) -> Iterator[str]:
        """Convert a file into a .txt"""

        if var_type is None:
            var_type = os.path.splitext(path)[1]

        if var_type[0] == ".":
            var_type = var_type[1:]
    
        if var_type not in cls.conversion_map:
            raise NotImplementedError(
                f"Unsupported file type : '{var_type}'."
                f" Supported types are : {list(cls.conversion_map)}"
            )

        return cls.conversion_map[var_type](var_type, **kwargs)