name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # Repo checkout

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        sudo apt install tree

    - name: Install dependencies with Poetry
      run: |
        poetry install --no-interaction --no-root

    - name: Run pytest (Network online)
      run: |
        poetry run pytest tests/ \
          --maxfail=1 \
          --user-agent="${{ github.server_url }}/${{ github.repository }} (${{ github.actor }})" \
          -m "not offline_simulation"

    - name: Run pytest (Network offline)
      run: |
        poetry run pytest tests/ \
          --maxfail=1 \
          --user-agent="${{ github.server_url }}/${{ github.repository }} (${{ github.actor }})" \
          -m "not offline_simulation"

    - name: Collect pytest logs
      if: always()
      run: |
        mkdir -p collected_logs
        
        # Iterate over each .tests directory
        find tests/ -type d -name ".tests" | while read dir; do
            echo "Processing: $dir" >> collected_logs/test_folders_copy.txt
            echo "Dir path: ${dir}" >> collected_logs/test_folders_copy.txt
        
            if [ -d "$dir" ] && [ "$(ls -A "$dir")" ]; then
                # Compute relative path
                rel_path="$dir"
                mkdir -p "collected_logs/$rel_path"
                # Copy contents
                rsync -a "$dir/"* "collected_logs/$rel_path/" # Should include hidden files 
                echo "Copied $dir" >> collected_logs/test_folders_copy.txt

            else
                echo "Skipping empty or missing folder: $dir" >> collected_logs/test_folders_copy.txt
            fi
            echo "" >> collected_logs/test_folders_copy.txt
        done
        
        echo "Full content :" >> collected_logs/test_folders_copy.txt
        tree -a ./collected_logs/ >> collected_logs/test_folders_copy.txt


    - name: Upload pytest logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-logs
        path: collected_logs
        include-hidden-files: true